services:
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

  smtp:
    image: mailhog/mailhog:latest
    restart: always
    ports:
      - "8025:8025"

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    image: fider:local
    environment:
      BASE_URL: ${BASE_URL}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      EMAIL_NOREPLY: ${EMAIL_NOREPLY}
      EMAIL_SMTP_HOST: smtp
      EMAIL_SMTP_PORT: "1025"
    command: ["/app/fider", "migrate"]
    depends_on:
      db:
        condition: service_healthy

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: fider:local
    restart: always
    environment:
      BASE_URL: ${BASE_URL}
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      EMAIL_NOREPLY: ${EMAIL_NOREPLY}
      EMAIL_SMTP_HOST: smtp
      EMAIL_SMTP_PORT: 1025
    depends_on:
      migrate:
        condition: service_completed_successfully
      smtp:
        condition: service_started
    ports:
      - "80:3000"

volumes:
  pg_data:
