name: OIDC Test

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test-oidc:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::222238779065:role/fider-github-actions
          aws-region: eu-west-2

      - name: Verify AWS identity
        run: aws sts get-caller-identity
